server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_boot_template}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none


app:
  security:
    issuer: ${APP_JWT_ISSUER:spring-boot-template}
    secret: ${APP_JWT_SECRET:F6RQWvFpYsEp5KCPRlOkWas7Q1rmC5wPbG1A05VCWg1xcSmaXqkHyBMEfJPRb5La}
    access-token-duration-in-seconds: ${APP_JWT_ACCESS_TOKEN_DURATION_IN_SECONDS:2700}
    refresh-token-duration-in-seconds: ${APP_JWT_REFRESH_TOKEN_DURATION_IN_SECONDS:86400}
    password-reset-duration-in-seconds:  ${APP_PASSWORD_RESET_DURATION_IN_SECONDS:900}
  recaptcha:
    enabled: ${APP_RECAPTCHA_ENABLED:false}
    secret-key: ${APP_RECAPTCHA_SECRET_KEY:secret-key}
    verify-url: ${APP_RECAPTCHA_VERIFY_URL:https://www.google.com/recaptcha/api/siteverify}
    score-threshold: ${APP_RECAPTCHA_SCORE_THRESHOLD:0.5}
  frontend:
    url: ${FRONTEND_URL:http://localhost:4200}
