server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/spring_boot_template}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  jpa:
    open-in-view: false
